{% set name = "clickhouse-driver" %}
{% set version = "0.2.1" %}
{% set sha256 = "8f446bdc38a676d4b345a4395cf913e47d1a694250a971ddd50c24e08029fc75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python >=3.4.*,<4
    - setuptools
    - wheel
  run:
    # 6/7/2021: Drop support Python 2.7
    - python >=3.4.*,<4
    - six
    - pytz
    - tzlocal <3.0

test:
  imports:
    - clickhouse_driver
    - clickhouse_driver.columns
    - clickhouse_driver.compression
    - clickhouse_driver.settings
    - clickhouse_driver.streams
    - clickhouse_driver.util
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mymarilyn/clickhouse-driver
  doc_url: https://clickhouse-driver.readthedocs.io/
  dev_url: https://github.com/mymarilyn/clickhouse-driver
  license: MIT
  summary: Python driver with native interface for ClickHouse
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
    - cpcloud
    - xmnlab
    - xhochy
