{% set name = "clickhouse-driver" %}
{% set version = "0.2.9" %}
{% set sha256 = "050ea4870ead993910b39e7fae965dc1c347b2e8191dcd977cd4b385f9e19f87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pytz
    - tzlocal
  run_constrained:
    - clickhouse-cityhash >=1.0.2.1 # extra:lz4
    - numpy >=1.12.0 # extra:numpy
    - pandas >=0.24.0 # extra:numpy

test:
  imports:
    - clickhouse_driver
    - clickhouse_driver.columns
    - clickhouse_driver.compression
    - clickhouse_driver.settings
    - clickhouse_driver.streams
    - clickhouse_driver.util
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mymarilyn/clickhouse-driver
  doc_url: https://clickhouse-driver.readthedocs.io/
  dev_url: https://github.com/mymarilyn/clickhouse-driver
  license: MIT
  summary: Python driver with native interface for ClickHouse
  description: ClickHouse Python Driver with native interface support
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
    - cpcloud
    - xmnlab
    - xhochy
