travis:
  secure:
    BINSTAR_TOKEN: KGCts3e+F/TcvM4E+zhrXPkgw1IDpVWiMFtiPBwyE4Eb/aev8ukoVIDUIdlFKhlNjuwgeCOsq8KBEIn3Ccu7J05vqw6sVdWl33idTeuaUpqIe9KnerjM4eLnfAPZcr7S0RyzWZCGwXHD2Sb6wsXJV+jNPZCNMd/y+Elt7TpCLdx7TtcUctmko3zzwDQ1haaRlqNg8+1p8mrTPDxUXFAp/EAyyojECO2gH/5haiE52gcdmh9pUbiv/E8haoM902sLMyEmk7TWWyiUu1nBQtOQx5aAwtggs2PVvSfcHJpvaUtLnF0FJCWaiykK3aFZUYT49h/lXUTS5dYyzBdpxmdkuvoP7PMMYudjnaZFkMrp50CGQ7JBfWYUv9/UxDGanvpBSDF0DujyWbN1KSF/kOctb0zIr8GJrQGSalcRpgZbArtaZRVYKkMNtTVBYdAs8C/GQ/+RvusUTvmZdxCOp3vkO+ecThfMkmBTCZpXBbrlX2kmMWzTWr/d+8/a9JXamE0qHWBF6gc4dMrxpGcmrNoIu3E1ESyXecJBa4eyx+DFj3HU+WyBrAyFjLpxlYTJBbrCxgPpLpkB6OLGa8zf3N60WuS37Z5A9FqDMRlj2bpt5OCdKTNGzIk1GetCmryDy9938rP/Ra8NfmWtbK/HQyAAd0W2oaeSsLmFn1YxpdmVTaY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
