travis:
  secure:
    BINSTAR_TOKEN: pKWHts1HIj7TKgUyKbmLCiwCKStgPVMeXRXV33p3tEddoZll5Xvliyx61Nz62ytJFHiP/rBGdHNunW9sYIKTY+oYbhgC02yQdkyCjoSGEs/wdYpEX4ehIRcBpwxxSkIpxpjMRPfhZ8GwX9h6PewqYcf0aRXNUasL3o/LEtq1i2ou6OBkkpXgAE1UHd3v0maTGq3a/uupcciQWi/Zp8hPXYYg+cL5MPOWpju7X3485IMe2SQO2osTiW1LRJpGo0Na5Puaz61BaE0rj9awaherCPCxHa301aIv5idHu0TOiP0zEHTBi6mmd0EP6yKG0Pn9dAurj/Pn4uL6sOIPOZwFM0FV/3ZgFVkf6m7xUrJLTKg84nsDus8oJzJ256Abmv0wihoAdvGnnyiNNg+R0fad9py62y7xsjIv10HvbDwSROism/zKIPZzqCBElgHZzyfONIpQ3SfaMJ/zpsugPqFFiILHyfAVtQ2rBMtXzQQOn4l4ymMwqJ05eGHJR+ztrlOsZw4nJDQNVdj5bEqdReAHyIn7hKAibm0B/PqP0HVOX8G9tUdiRY8W6ywwdn0+ziEWSyhl1CYgK1Alsd4DoeisfmY1YvfcpUKFueglgiDkEF+4oIKq4dxYkxNTtxNrZufoANjHpF4hBHegeyOjJM/P4SZWn0sHJzgpE/3nGlkUIXU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
