travis:
  secure:
    BINSTAR_TOKEN: ekcdriDmggJ63xL1FaJHARc8gniNIP1aRMKWKd1aCyzpgrBzI00jn7i/+aIm2utpt3i/1b37i761LaOm8yqE5HMQlnc+n3g1CP0em3vHVN8hqaEX3ICyPMf+XStvrdRC4mVDuwRH8tI1C1VpM8HOcqr7UqjgNvPyEhXVknQ3+m/HDU3/HTcQIljPZMKdY2GBpez65zonpbzijk9WbYd7HFyb3WbY4phrqyyU1+nb5n5cAUN/dFnuP6om4hv7shN19ehEE5hStJrKneI5PdGM6a0HitW5FBPIRIjDH2oZuIVjCwHbp3HqpHzFeA/R1jHecvZu77bIeRoexhZIshNK1R765OpfKGIcEIMGEpFlme58/ZYTk4dKymEsm8geyniimPRxETXOTI5WSZdLzaqOZ5eEdHdZhDpNqynIDTrPvCjD/hpmmrliPUVokdRpiB92RaGoW5XiTtIKLmCu0LLW3xNViLVAmuMPhuM+HKGjraqg+0FV1tMsPrYnbZItNIzGc7rzVfYNGkVmE6e9Yhqjy8WTLBfUKD5ODHuH1ChjdjNSbGW7HNkiENTn9Iwe5XiNtwKwjyQYiWx5KWhUxAxOQRO9MEcCmOIgPYkEiZNc/iirfDdDopUCDRssm/1KL/Ugx33JkwcEiH0mde225LwOuNJGa4aEFU97EPvRgrUIgGE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
